/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());

    int x = 2, y = 3;
    System.out.println("Sum of "+x+" and "+y+" is "+(x+y)+". Average is 2.5.");
  }
}
